name: Executar scraping a cada 5 minutos

on:
  schedule:
    - cron: '*/5 * * * *'     # Executa a cada 5 minutos (UTC)
  workflow_dispatch:           # Permite execução manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas selenium webdriver-manager

      - name: Executar script
        run: python script.py
